Validating models...

0 errors found
Django version 1.3.1, using settings 'greg1Project.settings'
Development server is running at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
----------------------------------------
Exception happened during processing of request from ('12.43.235.194', 63751)
